// Objective-C API for talking to github.com/dprotaso/cf/ios Go package.
//   gobind -lang=objc github.com/dprotaso/cf/ios
//
// File is generated by gobind. Do not edit.

#ifndef __GoCfios_H__
#define __GoCfios_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT void GoCfiosLogin(NSString* name, NSString* password);

FOUNDATION_EXPORT NSString* GoCfiosOrgs();

FOUNDATION_EXPORT void GoCfiosSetAPI(NSString* endpoint, BOOL disableSSL);

#endif
