// Objective-C API for talking to github.com/dprotaso/cf/ios Go package.
//   gobind -lang=objc github.com/dprotaso/cf/ios
//
// File is generated by gobind. Do not edit.

#ifndef __GoCfios_H__
#define __GoCfios_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT BOOL GoCfiosApps(NSData** ret0_, NSError** error);

FOUNDATION_EXPORT void GoCfiosInit(NSString* path);

FOUNDATION_EXPORT BOOL GoCfiosLogin(NSString* name, NSString* password, NSError** error);

FOUNDATION_EXPORT BOOL GoCfiosOrgs(NSData** ret0_, NSError** error);

FOUNDATION_EXPORT BOOL GoCfiosSetAPI(NSString* endpoint, BOOL disableSSL, NSError** error);

FOUNDATION_EXPORT BOOL GoCfiosSpaces(NSData** ret0_, NSError** error);

FOUNDATION_EXPORT BOOL GoCfiosTargetOrg(NSString* orgName, NSError** error);

FOUNDATION_EXPORT BOOL GoCfiosTargetSpace(NSString* spaceName, NSError** error);

#endif
